version: '3.7'
services:
  # REST API on NodeJS container
  app:
    container_name: lafs-api
    restart: always
    build: .
    ports:
      - '3000:3000'
    # Link to mongoDB container
    links:
      - mongo
    # Pass in environment variables for database host and name
    environment:
      - DB_HOST=mongo
      - DB_NAME=lafs-db
  # MongoDB storage container
  mongo:
    container_name: lafs-db
    image: 'mongo:4'
    ports:
      - '27017:27017'
    # Attach containers to external network
networks:
  default:
    external:
      name: lafs-net